<?php

return [
    [
        "strDrink" => "Tom Collins",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Collins glass",
        "strInstructions" => "In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a collins glass almost filled with ice cubes. Add the club soda. Stir and garnish with the cherry and the orange slice.",
        "strInstructionsIT" => "In uno shaker riempito a metà con cubetti di ghiaccio, unisci il gin, il succo di limone e lo zucchero.Mescolate e guarnite con la ciliegia e la fetta d'arancia.Filtrare in un bicchiere collins pieno di cubetti di ghiaccio.Aggiungi la soda club.Agitare bene.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Lemon juice",
        "strIngredient3" => "Sugar",
        "strIngredient4" => "Club soda",
        "strIngredient5" => "Maraschino cherry",
        "strIngredient6" => "Orange",
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "2 oz ",
        "strMeasure2" => "1 oz ",
        "strMeasure3" => "1 tsp superfine ",
        "strMeasure4" => "3 oz ",
        "strMeasure5" => "1 ",
        "strMeasure6" => "1 ",
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => "https://commons.wikimedia.org/wiki/File:Tom_Collins.jpg",
        "strImageAttribution" => "Will Shenton",
    ],
    [
        "strDrink" => "Lemon Elderflower Spritzer",
        "strTags" => "Summer, Fresh, Refreshing",
        "strCategory" => "Cocktail",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Pour all ingredients over ice, stir and enjoy!\r\n",
        "strInstructionsIT" => null,
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg",
        "strIngredient1" => "Elderflower cordial",
        "strIngredient2" => "Vodka",
        "strIngredient3" => "Soda Water",
        "strIngredient4" => "Fresh Lemon Juice",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "2 tsp",
        "strMeasure2" => "1 shot",
        "strMeasure3" => "1/3 cup",
        "strMeasure4" => "Top",
        "strMeasure5" => "",
        "strMeasure6" => "",
        "strMeasure7" => "",
        "strMeasure8" => null,

        "strImageSource" => "https://www.instagram.com/p/CNLYC2_sdlk",
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Hawaiian Cocktail",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Cocktail glass",
        "strInstructions" => "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" => "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/ujoh9x1504882987.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Triple sec",
        "strIngredient3" => "Pineapple juice",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "2 oz ",
        "strMeasure2" => "1/2 oz ",
        "strMeasure3" => "1 tblsp ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Belgian Blue",
        "strTags" => null,
        "strCategory" => "Soft Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Just pour all ingredients in the glass and stir...",
        "strInstructionsIT" => "Basta versare tutti gli ingredienti nel bicchiere e mescolare.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/jylbrq1582580066.jpg",
        "strIngredient1" => "Vodka",
        "strIngredient2" => "Coconut liqueur",
        "strIngredient3" => "Blue Curacao",
        "strIngredient4" => "Sprite",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "2 cl ",
        "strMeasure2" => "1 cl ",
        "strMeasure3" => "1 cl ",
        "strMeasure4" => "Fill with ",
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Radioactive Long Island Iced Tea",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Collins Glass",
        "strInstructions" => "Pour all ingredients over ice in a very tall glass. Sip cautiously.",
        "strInstructionsIT" => "Versare tutti gli ingredienti sul ghiaccio in un bicchiere molto alto.\r\nSorseggia con cautela.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/rdvqmh1503563512.jpg",
        "strIngredient1" => "Rum",
        "strIngredient2" => "Vodka",
        "strIngredient3" => "Tequila",
        "strIngredient4" => "Gin",
        "strIngredient5" => "Triple sec",
        "strIngredient6" => "Chambord raspberry liqueur",
        "strIngredient7" => "Midori melon liqueur",
        "strIngredient8" => "Malibu rum",

        "strMeasure1" => "1 oz ",
        "strMeasure2" => "1 oz ",
        "strMeasure3" => "1 oz ",
        "strMeasure4" => "1 oz ",
        "strMeasure5" => "1 oz ",
        "strMeasure6" => "1 oz ",
        "strMeasure7" => "1 oz ",
        "strMeasure8" => "1 oz ",

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Shot-gun",
        "strTags" => null,
        "strCategory" => "Shot",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Shot glass",
        "strInstructions" => "Pour one part Jack Daniels and one part Jim Beam into shot glass then float Wild Turkey on top.",
        "strInstructionsIT" => "Versare una parte di Jack Daniels e una parte diJim Beam nel bicchierino da shot, infine versare il Wild Turkey.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/2j1m881503563583.jpg",
        "strIngredient1" => "Jim Beam",
        "strIngredient2" => "Jack Daniels",
        "strIngredient3" => "Wild Turkey",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "1 part ",
        "strMeasure2" => "1 part ",
        "strMeasure3" => "1 oz ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Snowball",
        "strTags" => "Christmas",
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Place one ice cube in the glass and add 1 1/2 oz of Advocaat. Fill up the glass with lemonade and decorate with a slice of lemon. Serve at once.",
        "strInstructionsIT" => "Riempite il bicchiere con la limonata e decorate con una fetta di limone.\r\n",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/7ibfs61504735416.jpg",
        "strIngredient1" => "Advocaat",
        "strIngredient2" => "Lemonade",
        "strIngredient3" => "Lemon",
        "strIngredient4" => "Ice",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "1 1/2 oz ",
        "strMeasure2" => "8-10 oz cold ",
        "strMeasure3" => "1 slice ",
        "strMeasure4" => "cubes",
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Banana Strawberry Shake",
        "strTags" => null,
        "strCategory" => "Shake",
        "strAlcoholic" => "Non alcoholic",
        "strGlass" => "Highball Glass",
        "strInstructions" => "Blend all together in a blender until smooth.",
        "strInstructionsIT" => "Frullate tutto insieme in un frullatore fino a che non risulti liscio.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/vqquwx1472720634.jpg",
        "strIngredient1" => "Strawberries",
        "strIngredient2" => "Banana",
        "strIngredient3" => "Yoghurt",
        "strIngredient4" => "Milk",
        "strIngredient5" => "Honey",
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "1/2 lb frozen ",
        "strMeasure2" => "1 frozen ",
        "strMeasure3" => "1 cup plain ",
        "strMeasure4" => "1 cup ",
        "strMeasure5" => " to taste\n",
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "Dragonfly",
        "strTags" => null,
        "strCategory" => "Ordinary Drink",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "In a highball glass almost filled with ice cubes, combine the gin and ginger ale. Stir well. Garnish with the lime wedge.",
        "strInstructionsIT" => "In un bicchiere highball quasi riempito con cubetti di ghiaccio, unire il gin e la ginger ale. Mescolare bene. Guarnire con lo spicchio di lime.",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/uc63bh1582483589.jpg",
        "strIngredient1" => "Gin",
        "strIngredient2" => "Ginger ale",
        "strIngredient3" => "Lime",
        "strIngredient4" => null,
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "1 1/2 oz ",
        "strMeasure2" => "4 oz ",
        "strMeasure3" => "1 ",
        "strMeasure4" => null,
        "strMeasure5" => null,
        "strMeasure6" => null,
        "strMeasure7" => null,
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink" => "747 Drink",
        "strTags" => null,
        "strCategory" => "Cocktail",
        "strAlcoholic" => "Alcoholic",
        "strGlass" => "Highball glass",
        "strInstructions" => "Fill a Collins glass with ice.\r\nPour in vodka, lime cordial, and cranberry juice.\r\nFill up with Sprite.\r\nGarnish with a Lime wheel or some cranberries",
        "strInstructionsIT" => "\r\nRiempi un bicchiere Collins di ghiaccio.\r\nVersare la vodka, lo sciroppo di lime e il succo di mirtillo rosso.\r\nRiempi con Sprite.\r\nGuarnire con una fetta di lime o dei mirtilli rossi",
        "strDrinkThumb" => "https://www.thecocktaildb.com/images/media/drink/i9suxb1582474926.jpg",
        "strIngredient1" => "Vodka",
        "strIngredient2" => "Roses sweetened lime juice",
        "strIngredient3" => "Cranberry Juice",
        "strIngredient4" => "Sprite",
        "strIngredient5" => null,
        "strIngredient6" => null,
        "strIngredient7" => null,
        "strIngredient8" => null,

        "strMeasure1" => "1 oz",
        "strMeasure2" => "1 oz",
        "strMeasure3" => "1 oz",
        "strMeasure4" => "Top",
        "strMeasure5" => "",
        "strMeasure6" => "",
        "strMeasure7" => "",
        "strMeasure8" => null,

        "strImageSource" => null,
        "strImageAttribution" => null,
    ],
    [
        "strDrink"     => "Afterglow",
        "strTags"     => null,
        "strCategory"     => "Cocktail",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Highball Glass",
        "strInstructions"     => "Mix. Serve over ice.",
        "strInstructionsIT"     => "Servire con ghiaccio.Mescolare.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/vuquyv1468876052.jpg",
        "strIngredient1"     => "Grenadine",
        "strIngredient2"     => "Orange juice",
        "strIngredient3"     => "Pineapple juice",
        "strIngredient4"     => null,
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "1 part ",
        "strMeasure2"     => "4 parts ",
        "strMeasure3"     => "4 parts ",
        "strMeasure4"     => null,
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Alice Cocktail",
        "strTags"     => null,
        "strCategory"     => "Cocktail",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Cocktail glass",
        "strInstructions"     => "Shake well, strain into a large cocktail glass.",
        "strInstructionsIT"     => "Shakerare bene, filtrare in una coppetta da cocktail capiente.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/qyqtpv1468876144.jpg",
        "strIngredient1"     => "Grenadine",
        "strIngredient2"     => "Orange juice",
        "strIngredient3"     => "Pineapple juice",
        "strIngredient4"     => "Cream",
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "1 cl ",
        "strMeasure2"     => "1 cl ",
        "strMeasure3"     => "2 cl ",
        "strMeasure4"     => "4 cl ",
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Apello",
        "strTags"     => null,
        "strCategory"     => "Other / Unknown",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Collins Glass",
        "strInstructions"     => "Stirr. Grnish with maraschino cherry.",
        "strInstructionsIT"     => "Versare tutti gli ingredienti in un mixing glass. Mescolate.\r\nGuarnire con una ciliegia al maraschino.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/uptxtv1468876415.jpg",
        "strIngredient1"     => "Orange juice",
        "strIngredient2"     => "Grapefruit juice",
        "strIngredient3"     => "Apple juice",
        "strIngredient4"     => "Maraschino cherry",
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "4 cl ",
        "strMeasure2"     => "3 cl ",
        "strMeasure3"     => "1 cl ",
        "strMeasure4"     => "1 ",
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Holloween Punch",
        "strTags"     => null,
        "strCategory"     => "Punch / Party Drink",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Punch bowl",
        "strInstructions"     => "Take a bunch of grape juice and a bunch of fizzy stuff (club soda, ginger ale, lemonlime, whatever). Mix them in a punch bowl. Take orange sherbet and lime sherbet. Scoop out scoops and float them in the punch, let them melt a little so that a nasty film spreads all over the top of the punch but there are still \"bubbles\" in it in the form of sherbet scoops. Looks horrible, tastes just fine.",
        "strInstructionsIT"     => "Prendi un mazzetto di succo d'uva e un po 'di roba frizzante (club soda, ginger ale, sprite, qualunque cosa).\r\nMescolali in una ciotola da punch.\r\nPrendi il sorbetto all'arancia e il sorbetto al lime.\r\nEstrarre le palette e farle galleggiare nel punch, lasciarle sciogliere un po 'in modo che una pellicola sgradevole si diffonda su tutta la parte superiore del punch ma ci siano ancora delle \"bolle\" sotto forma di palline di sorbetto.\r\nSembra orribile, ha un buon sapore.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/lfeoe41504888925.jpg",
        "strIngredient1"     => "Grape juice",
        "strIngredient2"     => "Carbonated soft drink",
        "strIngredient3"     => "Sherbet",
        "strIngredient4"     => "Sherbet",
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => null,
        "strMeasure2"     => ", orange\n",
        "strMeasure3"     => null,
        "strMeasure4"     => null,
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Lemouroudji",
        "strTags"     => null,
        "strCategory"     => "Other / Unknown",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Highball Glass",
        "strInstructions"     => "Juice the lemons. Peel and grate the ginger. Place the grated ginger and a liberal dash of the cayenne pepper into a piece of cheesecloth, and tie it into a knot. Let soak in the water. After 15 minutes or so, add the sugar, and the lemon juice. Chill, and serve.",
        "strInstructionsIT"     => "Mettere lo zenzero grattugiato spolverato di pepe di Caienna in un pezzo di garza, annodalo e lascia che lo zenzero e il pepe di Caienna infondano l'acqua in modo che l'acqua assuma sapore (circa 15 minuti).\r\nAggiungere lo zucchero e il succo di limone e mescolare bene.\r\nRaffredda e servi freddo. (Puoi lasciare fuori il pepe di Caienna se lo desideri). Metti in frigo, aggiusta lo zucchero se necessario e servi.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/eirmo71487603745.jpg",
        "strIngredient1"     => "Ginger",
        "strIngredient2"     => "Water",
        "strIngredient3"     => "Lemon",
        "strIngredient4"     => "Sugar",
        "strIngredient5"     => "Cayenne pepper",
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "2 pieces ",
        "strMeasure2"     => "1 gal ",
        "strMeasure3"     => "1 lb ",
        "strMeasure4"     => "1 cup ",
        "strMeasure5"     => "ground ",
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Spiking coffee",
        "strTags"     => null,
        "strCategory"     => "Coffee / Tea",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Coffee mug",
        "strInstructions"     => "Incidentally, a pinch of cinnamon is indeed a nice addition to coffee but true heaven is a cardamom seed. Of course, you serve it in a coffee mug.",
        "strInstructionsIT"     => "Per inciso, un pizzico di cannella è davvero una bella aggiunta al caffè. Servire in una tazza da caffè.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/isql6y1487602375.jpg",
        "strIngredient1"     => "Coffee",
        "strIngredient2"     => "Cinnamon",
        "strIngredient3"     => null,
        "strIngredient4"     => null,
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => null,
        "strMeasure2"     => null,
        "strMeasure3"     => null,
        "strMeasure4"     => null,
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Thai Iced Tea",
        "strTags"     => null,
        "strCategory"     => "Coffee / Tea",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Highball glass",
        "strInstructions"     => "Combine Thai tea (i.e., the powder), boiling water, and sweetened condensed milk, stir until blended. Pour into 2 tall glasses filled with ice cubes. Garnish with mint leaves. Makes 2 servings.",
        "strInstructionsIT"     => "Combina il tè tailandese (la polvere), l'acqua bollente e il latte condensato zuccherato, mescolare fino a quando non si saranno amalgamati.\r\nVersare in 2 bicchieri alti pieni di cubetti di ghiaccio.\r\nGuarnire con foglie di menta.\r\nPer 2 porzioni.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/trvwpu1441245568.jpg",
        "strIngredient1"     => "Tea",
        "strIngredient2"     => "Water",
        "strIngredient3"     => "Condensed milk",
        "strIngredient4"     => "Ice",
        "strIngredient5"     => "Mint",
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "1/4 cup Thai ",
        "strMeasure2"     => "1/2 cup boiling ",
        "strMeasure3"     => "2 tsp sweetened ",
        "strMeasure4"     => "cubes",
        "strMeasure5"     => "garnish",
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Strawberry Lemonade",
        "strTags"     => null,
        "strCategory"     => "Punch / Party Drink",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Collins Glass",
        "strInstructions"     => "Throw everything into a blender and mix until fairly smooth. Serve over ice.",
        "strInstructionsIT"     => "Getta tutto in un frullatore e mescola fino a che non sia abbastanza liscio.\r\nServire con ghiaccio.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/spvvxp1468924425.jpg",
        "strIngredient1"     => "Lemon",
        "strIngredient2"     => "Sugar",
        "strIngredient3"     => "Strawberries",
        "strIngredient4"     => "Water",
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "Juice of 1 ",
        "strMeasure2"     => "1 tblsp ",
        "strMeasure3"     => "8-10 ripe ",
        "strMeasure4"     => "1 cup ",
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Rail Splitter",
        "strTags"     => null,
        "strCategory"     => "Cocktail",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Highball glass",
        "strInstructions"     => "Mix sugar syrup with lemon juice in a tall glass. Fill up with ginger ale.",
        "strInstructionsIT"     => "Mescolare lo sciroppo di zucchero con il succo di limone in un bicchiere alto.Riempi di ginger ale.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/stsuqq1441207660.jpg",
        "strIngredient1"     => "Sugar syrup",
        "strIngredient2"     => "Lemon juice",
        "strIngredient3"     => "Ginger ale",
        "strIngredient4"     => null,
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "2 tsp ",
        "strMeasure2"     => null,
        "strMeasure3"     => null,
        "strMeasure4"     => null,
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
    [
        "strDrink"     => "Orangeade",
        "strTags"     => null,
        "strCategory"     => "Cocktail",
        "strAlcoholic"     => "Non alcoholic",
        "strGlass"     => "Highball glass",
        "strInstructions"     => "Place some ice cubes in a large tumbler or highball glass, add lemon juice, orange juice, sugar syrup, and stir well. Top up with cold soda water, serve with a drinking straw.",
        "strInstructionsIT"     => "Mettere alcuni cubetti di ghiaccio in un grande bicchiere tumbler o highball, aggiungere il succo di limone, il succo d'arancia, lo sciroppo di zucchero e mescolare bene.Rabboccare con acqua fredda di soda, servire con una cannuccia.",
        "strDrinkThumb"     => "https://www.thecocktaildb.com/images/media/drink/ytsxxw1441167732.jpg",
        "strIngredient1"     => "Lemon juice",
        "strIngredient2"     => "Orange juice",
        "strIngredient3"     => "Sugar syrup",
        "strIngredient4"     => "Soda water",
        "strIngredient5"     => null,
        "strIngredient6"     => null,
        "strIngredient7"     => null,
        "strIngredient8"     => null,
        "strMeasure1"     => "5 cl ",
        "strMeasure2"     => "15 cl ",
        "strMeasure3"     => "2-3 cl ",
        "strMeasure4"     => null,
        "strMeasure5"     => null,
        "strMeasure6"     => null,
        "strMeasure7"     => null,
        "strMeasure8"     => null,
        "strImageSource"     => null,
        "strImageAttribution"     => null,
    ],
];
